### ISSUE TITLE
Добавить подпись источника поста

### ISSUE THREAD

**Issue by smotim** [qwertyadrian/TG_AutoPoster#17]
Хотелось бы сообщения из некоторых источников подписывать. Первой строчкой в сообщении название группы, из которой пост. Можно через телеграмовское форматирование сразу ссылку прятать внутри названия.

**Comment by qwertyadrian** [comment]
В релизе 3.4.0 будут добавлены параметры файла конфигурации `header` и `footer`, с помощью которых можно будет добавить произвольный текст (с форматированием) в начало и конец сообщения соответственно.
Для тестирования уже доступна предварительная версия 3.4.0b1.

**Comment by smotim** [comment]
Это еще лучше, спасибо. А можешь в примере конфига добавить строчку с примером?

**Comment by qwertyadrian** [comment]
Да, пример будет добавлен.
А пока я оставлю файл конфигурации здесь:
```yaml
domains:
    id1:
        channel: '@channel'
        footer: '[Footer](https://github.com)'
        header: 'Header'
settings: # Если указать параметры в settings то они будут применяться для всех источников, у которых они не переопределены
    footer: 'default_footer'
    header: 'default_footer'
telegram:
    api_hash: 1ff4**e6a305
    api_id: 123456
    bot_token: 5754**eIDo
vk:
    token: cdb***688ca3f
```
