### ISSUE TITLE
bug'ованый

### ISSUE THREAD

**Issue by mrgulka** [qwertyadrian/TG_AutoPoster#19]
**Опишите ошибку**
Четкое и краткое описание того, что произошло.

— после примерно 24 часов исправной работы бот не пересылает новые посты

**Как получить ошибку**
Шаги для воспроизведения ошибки:

— я заметил, что прошлый номер поста не совпадает с только что появившемся на 20-100, скорее всего это связано с тем что бот не видит новых постов 

**Ожидаемое поведение**
Четкое и краткое описание того, что вы ожидали.

— выше 

**Лог-файл**
Загрузите лог-файл бота, запущенного в режиме отладки (параметр `--debug`).

— в консоль исправно присылаются логи о get_poste через каждые 2 часа

**Ваш ПК (пожалуйста, укажите следующую информацию):**
 - OS: [e.g. Windows]
 - Python Version: [e.g. 3.6]
 - Версия бота [e.g. 3.2.0]
 - Источник установки (GitHub, PyPI, Docker Hub)
 - Приложите файл конфигурации бота
 - Ссылка на проблемный пост

— linux 20

**Дополнительная информация**
Любая дополнительная информация может быть размещена здесь

— жду вопросы

**Comment by mrgulka** [comment]
я попробовал рестартить через cron его каждые сутки, но я не очень умею програмить(

**Comment by qwertyadrian** [comment]
Поскольку лог-файл не был предоставлен. Предположу, что ошибок нет. Следовательно, бот не отправляет посты либо потому, что они рекламные, либо id последнего отправленного поста больше, чем id последнего поста в группе.

**Comment by mrgulka** [comment]
[logs.zip](https://github.com/qwertyadrian/TG_AutoPoster/files/9636850/logs.zip)
@qwertyadrian лог файлы. помогите исправить( жду вопросов

**Comment by mrgulka** [comment]
```
domains:
    https://vk.com/avatar_film:
        channel: '@avatar_universe'
        last_id: 105720
        last_story_id: 0
        pinned_id: 105439
        use_long_poll: true
    https://vk.com/gulstore:
        channel: -1001307034582
        last_id: 24
        last_story_id: 0
        pinned_id: 0
        use_long_poll: true
settings:
    admins_id:
    - 453370423
    blacklist: '#(\w+)'
    disable_notification: true
    disable_web_page_preview: false
    posts_count: 150
    send_reposts: true
    send_stories: true
    sign_posts: false
telegram:
    api_hash: 
    api_id: 
    bot_token: 
vk:
    login: ''
    password: ''
    token: 
```
