### ISSUE TITLE
Нет ссылок на статьи

### ISSUE THREAD

**Issue by smotim** [qwertyadrian/TG_AutoPoster#29]
**Опишите ошибку**
Бот не добавляет ссылки на статьи, только пишет их заголовки. Пример:
![изображение](https://user-images.githubusercontent.com/57951811/222252006-9ad61308-4577-4112-a4e8-4a813f1376d8.png)

**Как получить ошибку**
Мой конфиг:
```
    https://vk.com/****:
        channel:
        - ****
        - ****
        header: 'Источник:  [*** ***](https://*****)'
        last_id: 1585
        last_story_id: 0
        pinned_id: 0
settings:
    admins_id:
    - ********
    disable_web_page_preview: true
    send_reposts: true
    what_to_send:
    - all
```
Авторизация в ВК через токен
